package com.myspace.recursoshumanos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class persona implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "cedula")
	private java.lang.Integer cedula;

	public persona() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Integer getCedula() {
		return this.cedula;
	}

	public void setCedula(java.lang.Integer cedula) {
		this.cedula = cedula;
	}

	public persona(java.lang.String id, java.lang.Integer cedula) {
		this.id = id;
		this.cedula = cedula;
	}

}